[Icon Theme]
Name=Monochrome Icons
Comment=White drawings on black faces; GTK and Qt compatible native-name overlay.
Inherits=WhiteSur-dark,hicolor
Directories=apps/16,apps/22,apps/24,apps/32,apps/40,apps/48,apps/64,apps/96,apps/128,apps/256,categories/16,categories/22,categories/24,categories/32,categories/40,categories/48,categories/64,categories/96,categories/128,categories/256

[apps/16]
Size=16
Type=Fixed
Context=Applications

[apps/22]
Size=22
Type=Fixed
Context=Applications

[apps/24]
Size=24
Type=Fixed
Context=Applications

[apps/32]
Size=32
Type=Fixed
Context=Applications

[apps/40]
Size=40
Type=Fixed
Context=Applications

[apps/48]
Size=48
Type=Fixed
Context=Applications

[apps/64]
Size=64
Type=Fixed
Context=Applications

[apps/96]
Size=96
Type=Fixed
Context=Applications

[apps/128]
Size=128
Type=Fixed
Context=Applications

[apps/256]
Size=256
Type=Fixed
Context=Applications

[categories/16]
Size=16
Type=Fixed
Context=Categories

[categories/22]
Size=22
Type=Fixed
Context=Categories

[categories/24]
Size=24
Type=Fixed
Context=Categories

[categories/32]
Size=32
Type=Fixed
Context=Categories

[categories/40]
Size=40
Type=Fixed
Context=Categories

[categories/48]
Size=48
Type=Fixed
Context=Categories

[categories/64]
Size=64
Type=Fixed
Context=Categories

[categories/96]
Size=96
Type=Fixed
Context=Categories

[categories/128]
Size=128
Type=Fixed
Context=Categories

[categories/256]
Size=256
Type=Fixed
Context=Categories
